@startuml

openjfx.org.Application <|== InvManager
InvManager -- MainWindowController
MainWindowController -- SceneManager
MainWindowController o-- FileManager
MainWindowController o-- InventoryModel
AddItemWindowController --|> MainWindowController
EditItemWindowController --|> MainWindowController
RemoveItemWindowController --|> MainWindowController
SearchItemWindowController --|> MainWindowController
InventoryModel *-- InventoryItem

Class InvManager {
    main()
    start()
}
Class SceneManager {
    initialize()
    loadScene(String)
}
Class MainWindowController {
    items: InventoryModel
    scenes: SceneManager
    files: FileManager
    addItemButtonClicked()
    editItemButtonClicked()
    removeItemButtonClicked()
    searchItemButtonClicked()
    saveInventoryAsTSVButtonClicked()
    saveInventoryAsHTMLButtonClicked()
    saveInventoryAsJSONButtonClicked()
}
Class AddItemWindowController {

}
Class EditItemWindowController {

}
Class RemoveItemWindowController {

}
Class SearchItemWindowController {

}
Class FileManager {
    saveAsTSV()
    saveAsHTML()
    saveAsJSON()
}
Class InventoryModel {
    - ObservableList<InventoryItem>
}
Class InventoryItem {
    value: SimpleDoubleProperty
    serial: SimpleStringProperty
    name: SimpleStringProperty
    getValue()
    getSerial()
    getName()
    setValue()
    setSerial()
    setName()
}
@enduml