@startuml

openjfx.org.Application <|== InvManager
InvManager -- MainWindowController
MainWindowController -- SceneManager
MainWindowController o-- InventoryModel
AddItemWindowController --|> MainWindowController
EditItemWindowController --|> MainWindowController
InventoryModel *-- InventoryItem
InventoryModel o-- FileManager

Class InvManager {
    main()
    start()
}
Class SceneManager {
    initialize()
    loadScene(String)
}
Class MainWindowController {
    popup: Stage
    model: InventoryModel
    scenes: SceneManager
    table: TableView
    valueColumn: tableColumn
    serialColumn: tableColumn
    nameColumn: tableColumn
    editButton: Button
    removeButton: Button
    clearSearchButton: Button

    initialize()
    AddItemButtonClicked()
    EditItemButtonClicked()
    RemoveItemButtonClicked()
    SearchItemButtonClicked()
    InstructionsButtonClicked()
    SaveAsButtonClicked()
    LoadButtonClicked()
    CloseButtonClicked()
    refreshTable()
    tableClicked()
    ClearSearchButtonClicked()
}
Class AddItemWindowController {
    nameBox: TextField
    serialBox: TextField
    valueBox: TextField

    initialize()
    addButtonClicked()
    cancelButtonClicked()
}
Class EditItemWindowController {
    nameBox: TextField
    serialBox: TextField
    valueBox: TextField

    initialize()
    editButtonClicked()
    cancelButtonClicked()
}
Class FileManager {
    saveFile(ObservableList, File, String)
    saveTSV(ObservableList, File)
    saveHTML(ObservableList, File)
    saveJSON(ObservableList, File)
    loadFile(File, String)
    loadTSV(File)
    loadHTML(File)
    loadJSON(File)
}
Class InventoryModel {
    - ObservableList<InventoryItem>
    files: FileManager

    addItem(String, String, String)
    editItem(String, String, String)
    removeItem()
    getSelectedItem()
    getInventory()
    searchinventory()
    saveTable(Stage)
    loadTable(Stage)
}
Class InventoryItem {
    value: SimpleDoubleProperty
    serial: SimpleStringProperty
    name: SimpleStringProperty
    getValue()
    getSerial()
    getName()
    setValue()
    setSerial()
    setName()
}
@enduml